use_frameworks!
target 'MiniProjet'
pod 'GoogleSignIn'
pod 'Alamofire'
pod 'Cosmos', '~> 23.0'
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'MessageKit'

pod 'Scaledrone', '~> 0.5.0'

# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Messaging'
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    

end
